### ISSUE TITLE
todo list before v2.0.0-rc 

### ISSUE THREAD

**Issue by antondlr** [sigp/lighthouse-ui#238]
- [x] provide default .env file if none provided
- [x] clean up logging from the container
- [x] better error handling on startup (i.e., APIs unavailable) 
- [ ] prepare lighthouse-book for new version
- [x] update README
- [x] update workflows
- [x] 3rd party testing / look-over: is the container in its current form user-friendly and stable enough?
- [x] add a docker-compose file 
- [x] bump version in `package.json`
- [x] assign a license in `backend/package.json`
